language: node_js
node_js:
- "stable"

cache:
  directories:
    - "node_modules"

before_script:
- npm run start

before_install:
- npm install -g supertest
- npm install -g mocha

after_success:
- npm run coverage
- npm run report-coverage
